name: 'Continuous Integration'
on:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        platform: [ 'ubuntu-latest', 'macos-latest' ]
        php: [ '8.0', '8.1', '8.2' ]
    name: 'Testing ${{ matrix.php }}/${{ matrix.platform }}'
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: xdebug
        tools: composer
    - run: |
        make ci
        composer validate --strict
        composer install
    - run: vendor/bin/phpunit
    - run: vendor/bin/infection --threads=4