name: 'Continuous Integration'
on:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2' ]
    name: 'Testing on ${{ matrix.php }}'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xdebug
          tools: composer
      - run: |
          make ci
          composer validate --strict
          composer install
      - run: vendor/bin/phpunit
      - run: vendor/bin/infection --threads=4
  psalm:
    name: 'Executing Psalm analyzer'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - run: |
          make ci
          composer validate --strict
          composer install
          vendor/bin/psalm --report=tests/_output/psalm/report.sarif
      - name: 'Upload Security Analysis results to GitHub'
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tests/_output/psalm/report.sarif
