name: 'Continuous Integration'
on:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2' ]
    name: 'Testing on ${{ matrix.php }}'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: xdebug
        tools: composer
    - name: 'Preparing environment'
      run: |
        make ci
        composer validate --strict
        composer install
    - run: vendor/bin/phpunit
    - run: vendor/bin/infection --threads=4
  psalm-codeql:
    name: 'Get Psalm CodeQL Report'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - name: 'Preparing environment'
      run: |
        make ci
        composer validate --strict
        composer install
    - name: 'Running Psalm'
      continue-on-error: true
      run: vendor/bin/psalm --output-format=github --report=tests/_output/psalm/report.sarif
    - name: 'Upload Security Analysis results to GitHub'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: tests/_output/psalm/report.sarif
